/** Scoped React/browser verification, with its own D: profile and output only.
 * Uses installed esbuild, Edge and Node's WebSocket. Never starts official DSH.
 */
import { build } from 'esbuild'
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { createServer } from 'node:http'
import { spawn } from 'node:child_process'
import { resolve, join } from 'node:path'
const collectionsOnly = process.argv.includes('--collections-only')
const versionsOnly = process.argv.includes('--versions-only')
const scrollOnly = process.argv.includes('--scroll-only')
const skinsOnly = process.argv.includes('--skins-only')
const listingsOnly = process.argv.includes('--listings-only')
const compatibilityOnly = process.argv.includes('--compatibility-only')
const settingsOnly = process.argv.includes('--settings-only')
const taskHistoryOnly = process.argv.includes('--task-history-only')
const trialOnly = process.argv.includes('--trial-only')
const defaultOutput = compatibilityOnly ? 'D:/eac-market-verify/implementation-20260928/C-UI/compatibility' : listingsOnly || skinsOnly ? `D:/eac-market-verify/distribution-20260928/ui/${listingsOnly ? 'listings' : 'skins'}-${Date.now()}` : scrollOnly ? 'D:/eac-market-verify/skin-market-20260928/ui' : 'D:/eac-market-verify/implementation-20260928/C-UI' + (versionsOnly ? '/versions' : collectionsOnly ? '/collections' : '')
const output = process.env.EAC_BROWSER_CHECK_OUT ?? defaultOutput
console.log(`Evidence: ${output}`)
mkdirSync(output, { recursive: true })
await build({ entryPoints: ['tests/client/browser-fixture.tsx'], bundle: true, format: 'iife', platform: 'browser', jsx: 'automatic', outfile: join(output, 'browser-fixture.js'), alias: { react: resolve('packages/market/node_modules/react'), 'react-dom': resolve('packages/market/node_modules/react-dom') }, define: { 'process.env.NODE_ENV': '"development"' } })
const server = createServer((req, res) => {
  if (req.url === '/fixture.js') { res.setHeader('Content-Type', 'text/javascript'); res.end(readFileSync(join(output, 'browser-fixture.js'))) }
  else { res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.end('<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>合成 UI 回归</title><style>html,body{height:100%;margin:0}#root{height:100%}</style></head><body><div id="root"></div><script src="/fixture.js"></script></body></html>') }
})
await new Promise((done) => server.listen(0, '127.0.0.1', done))
const profile = join(output, `edge-profile-${Date.now()}`)
const browser = spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', ['--headless=new', '--disable-gpu', '--no-first-run', '--no-default-browser-check', '--disable-background-networking', '--disable-component-update', '--disable-sync', `--user-data-dir=${profile}`, '--remote-debugging-port=0', 'about:blank'], { windowsHide: true, stdio: 'ignore' })
const pause = (ms) => new Promise((done) => setTimeout(done, ms))
const results = []
let ws
let send
async function check(name, operation) { if (trialOnly && !name.startsWith('试用回归：') || taskHistoryOnly && !name.startsWith('任务记录：') || settingsOnly && !name.startsWith('设置：') || compatibilityOnly && !name.startsWith('兼容：') || listingsOnly && !name.startsWith('登记：') || skinsOnly && !name.startsWith('皮肤：') && !name.startsWith('滚动：') || collectionsOnly && !name.startsWith('组合：') || versionsOnly && !name.startsWith('版本：') || scrollOnly && !name.startsWith('滚动：')) return; try { await operation(); results.push({ name, status: 'passed' }) } catch (error) { results.push({ name, status: 'failed', error: error.message }) } }
try {
  for (let i = 0; i < 150 && !existsSync(join(profile, 'DevToolsActivePort')); i++) await pause(100)
  const port = readFileSync(join(profile, 'DevToolsActivePort'), 'utf8').split('\n')[0]
  const tabs = await fetch(`http://127.0.0.1:${port}/json/list`).then((r) => r.json())
  ws = new WebSocket(tabs.find((tab) => tab.type === 'page').webSocketDebuggerUrl)
  await new Promise((done, reject) => { ws.addEventListener('open', done, { once: true }); ws.addEventListener('error', reject, { once: true }) })
  let serial = 0
  const pending = new Map()
  ws.addEventListener('message', (event) => { const data = JSON.parse(event.data); const entry = pending.get(data.id); if (entry) { clearTimeout(entry.timer); pending.delete(data.id); data.error ? entry.reject(new Error(data.error.message)) : entry.resolve(data.result) } })
  send = (method, params = {}) => new Promise((resolveRequest, reject) => { const id = ++serial; const timer = setTimeout(() => { pending.delete(id); reject(new Error(`CDP timeout: ${method}`)) }, 15_000); pending.set(id, { resolve: resolveRequest, reject, timer }); ws.send(JSON.stringify({ id, method, params })) })
  const evaluate = async (expression) => { const result = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text); return result.result.value }
  const expect = async (expression, message) => { if (!await evaluate(expression)) throw new Error(message) }
  const until = async (expression) => { for (let i = 0; i < 100; i++) { if (await evaluate(expression)) return; await pause(30) } throw new Error(`DOM timeout: ${expression}`) }
  const click = async (text, scope = 'document') => { await evaluate(`(() => { const button = [...${scope}.querySelectorAll('button')].find(e => e.textContent.trim() === ${JSON.stringify(text)}); if (!button || button.disabled) throw new Error('button missing or disabled: ' + ${JSON.stringify(text)}); button.click() })()`); await pause(50) }
  const clickSelector = async (selector) => { const encoded = JSON.stringify(selector); await evaluate(`document.querySelector(${encoded}).scrollIntoView({block:'center'})`); await pause(80); const rect = JSON.parse(await evaluate(`(() => { const r=document.querySelector(${encoded}).getBoundingClientRect(); return JSON.stringify({x:r.x,y:r.y,width:r.width,height:r.height}) })()`)); const x=rect.x+rect.width/2, y=rect.y+rect.height/2; await send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1}); await send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',clickCount:1}); await pause(80) }
  const render = async (name) => { await evaluate(`fixture.render(${JSON.stringify(name)})`); await pause(100) }
  const input = async (id, text) => { await evaluate(`(() => { const el = document.getElementById(${JSON.stringify(id)}); Object.getOwnPropertyDescriptor(el.tagName === 'TEXTAREA' ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype, 'value').set.call(el, ${JSON.stringify(text)}); el.dispatchEvent(new Event('input', {bubbles:true})); })()`); await pause(30) }
  const theme = async (dark) => {
    await evaluate(`document.documentElement.style.cssText=${JSON.stringify(dark ? '--dsw-alias-bg-base:#141414;--dsw-alias-bg-layer-1:#232323;--dsw-alias-bg-layer-2:#303030;--dsw-alias-label-primary:#eeeeee;--dsw-alias-label-secondary:#b8b8b8;--dsw-alias-label-tertiary:#aaaaaa;--dsw-alias-border-l1:#4a4a4a;--dsw-alias-border-l3:#666666;--dsw-alias-link:#8aafff;--dsw-alias-state-business-primary:#386ad9;' : '')}`)
  }
  await send('Page.enable')
  await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
  await send('Page.navigate', { url: `http://127.0.0.1:${server.address().port}` })
  await until('!!window.fixture && document.body.innerText.includes("发现适合你的插件")')

  for (const [width, dark] of [[1280, false], [480, true]]) {
    await check('试用回归：无推荐无图片的大海报与窄屏 ' + width, async () => {
      await send('Emulation.setDeviceMetricsOverride', { width, height: 900, deviceScaleFactor: 1, mobile: false }); await theme(dark); await render('trial-fallback')
      await until('!!document.querySelector(".eac-market__poster--fallback")')
      await expect('document.querySelector("#featured-title").textContent === "插件探索" && document.body.innerText.includes("不代表团队精选或评分")', 'directory spotlight was missing or falsely curated')
      await expect('!document.querySelector(".eac-market__score-section") && fixture.stats.plans.length === 0 && fixture.stats.starts.length === 0', 'browsing invented scores or performed installation writes')
      await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'poster overflows the viewport')
      await expect('document.querySelector(".eac-market__poster-stage").getBoundingClientRect().height >= 220', 'poster collapsed into a small card')
      const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); writeFileSync(join(output, 'trial-fallback-' + width + (dark ? '-dark' : '-light') + '.png'), Buffer.from(shot.data, 'base64'))
    })
  }
  await check('试用回归：破图仍保留文字海报和详情入口', async () => {
    await render('trial-broken-poster'); await until('!!document.querySelector(".eac-market__poster--fallback")')
    await click('查看详情', 'document.querySelector(".eac-market__poster-copy")')
    await expect('document.querySelector("h1").textContent.includes("目录中的") && fixture.stats.starts.length === 0', 'broken image disabled the detail flow')
  })
  await check('试用回归：目标状态阻断不误报无关插件风险、不提供绕过勾选', async () => {
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false }); await theme(false); await render('trial-environment-blocked')
    await click('查看安装方案', 'document.querySelector(".eac-market__poster-copy")'); await until('document.body.innerText.includes("安装目标状态待核对")')
    await expect('document.body.innerText.includes("这不是对无关插件的风险判定") && !document.querySelector(".eac-modal input[type=checkbox]")', 'target blocker was conflated with optional risk consent')
    await expect('[...document.querySelectorAll("button")].find(button => button.textContent === "确认安装").disabled && fixture.stats.starts.length === 0', 'target state could start installation')
    const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); writeFileSync(join(output, 'trial-environment-blocked-1280.png'), Buffer.from(shot.data, 'base64'))
    await click('查看官方插件页'); await expect('fixture.stats.official > 0', 'official recovery action is not wired')
    await click('重新预检'); await until('fixture.stats.plans.length === 2'); await expect('fixture.stats.starts.length === 0', 'retry bypassed the target-state barrier')
  })
  await check('试用回归：无关库存未知不阻断目标安装', async () => {
    await render('trial-unrelated-inventory'); await click('查看安装方案', 'document.querySelector(".eac-market__poster-copy")')
    await until('document.body.innerText.includes("确认安装")')
    await expect('!document.body.innerText.includes("安装目标状态待核对") && ![...document.querySelectorAll("button")].find(button => button.textContent === "确认安装").disabled', 'unrelated inventory uncertainty blocked the target plan')
    await click('确认安装'); await until('fixture.stats.starts.length === 1')
    const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); writeFileSync(join(output, 'trial-unrelated-inventory-1280.png'), Buffer.from(shot.data, 'base64'))
  })
  await check('试用回归：未验证浏览中性，安装只需最终明确确认', async () => {
    await render('trial-fallback'); await click('全部插件')
    await expect('!!document.querySelector(".eac-market__status[data-tone=neutral]") && !!document.querySelector(".eac-market__status[data-tone=danger]")', 'risk-neutral listing removed a hard incompatibility warning')
    await click('查看安装方案', 'document.querySelector(".eac-market__plugin-card")'); await until('document.body.innerText.includes("确认安装")')
    await expect('!document.querySelector(".eac-market__install-consent") && fixture.stats.plans[0].selections.every(item => item.tryUnverified === false) && ![...document.querySelectorAll("button")].find(button => button.textContent === "确认安装").disabled', 'native-like install was not ready')
    await click('确认安装'); await until('fixture.stats.starts.length === 1')
  })
  await check('试用回归：手动暂停不被鼠标离开撤销，后台回来恢复可轮播', async () => {
    await evaluate('window._trialIntervals = new Map(); window._trialSetInterval = window.setInterval; window._trialClearInterval = window.clearInterval; window.setInterval = (fn, delay, ...args) => { const id = window._trialSetInterval(fn, delay, ...args); if (delay === 6500) window._trialIntervals.set(id, fn); return id; }; window.clearInterval = id => { window._trialIntervals.delete(id); window._trialClearInterval(id); };')
    try {
      await render('trial-fallback'); await until('window._trialIntervals.size === 1')
      await evaluate('Object.defineProperty(document, "hidden", { configurable: true, value: true }); document.dispatchEvent(new Event("visibilitychange"))'); await until('window._trialIntervals.size === 0')
      await evaluate('Object.defineProperty(document, "hidden", { configurable: true, value: false }); document.dispatchEvent(new Event("visibilitychange"))'); await until('window._trialIntervals.size === 1')
      await click('暂停')
      await evaluate('const poster = document.querySelector(".eac-market__featured"); poster.dispatchEvent(new MouseEvent("mouseover", { bubbles: true })); poster.dispatchEvent(new MouseEvent("mouseout", { bubbles: true, relatedTarget: document.body }));')
      await expect('window._trialIntervals.size === 0 && !!document.querySelector("button[aria-label=继续轮播]")', 'manual pause was overwritten by interaction pause')
    } finally {
      await evaluate('delete document.hidden; document.dispatchEvent(new Event("visibilitychange")); window.setInterval = window._trialSetInterval; window.clearInterval = window._trialClearInterval;')
    }
  })

  await check('发现页四区块：首推、推荐皮肤、高分插件、高分skill', async () => {
    await render('all-sections')
    await expect('document.body.innerText.includes("团队精选") && document.body.innerText.includes("皮肤推荐") && document.body.innerText.includes("高分插件") && document.body.innerText.includes("高分 skill")', 'discovery sections are incomplete')
  })

  await check('版本：同ID点击旧版本详情仍展示并预检该确切版本', async () => {
    await render('versions-home'); await click('全部插件')
    await click('查看详情', "[...document.querySelectorAll('.eac-market__plugin-card')].find(el => el.querySelector('h3').textContent === '精确版本 1.0.0')")
    await expect('document.querySelector("h1").textContent === "精确版本 1.0.0"', 'detail switched to another version with the same ID')
    await click('安装'); await until('fixture.stats.plans.length === 1')
    await expect('fixture.stats.plans[0].selections[0].targetVersion === "1.0.0"', 'detail preflight selected the wrong version')
  })
  await check('版本：公共套餐按component.version预检，不取第一个同ID插件', async () => {
    await send('Page.navigate', { url: `http://127.0.0.1:${server.address().port}` });
    await until('!!window.fixture && document.body.innerText.includes("发现适合你的插件")');
    await render('versions-home'); await until("([...document.querySelectorAll('button')].some(b => b.textContent.trim()==='查看套餐变更' && !b.disabled))"); await click('查看套餐变更'); await until('fixture.stats.plans.length === 1')
    await expect('fixture.stats.plans[0].packId === "versioned-pack" && fixture.stats.plans[0].selections[0].targetVersion === "1.0.0"', 'Pack selected the wrong version')
  })
  await check('版本：我的插件与旧版详情的默认更新均选择最高已登记兼容版本', async () => {
    await render('versions-installed'); await click('我的插件'); await click('更新到 2.0.0'); await until('fixture.stats.plans.length === 1')
    await expect('fixture.stats.plans[0].selections[0].targetVersion === "2.0.0"', 'inventory chose an invalid or unregistered update')
    await click('关闭'); await click('全部插件')
    await click('查看详情', "[...document.querySelectorAll('.eac-market__plugin-card')].find(el => el.querySelector('h3').textContent === '精确版本 1.0.0')")
    await expect('document.querySelector("h1").textContent === "精确版本 1.0.0"', 'installed detail selected another version')
    await click('更新到 2.0.0'); await until('fixture.stats.plans.length === 2')
    await expect('fixture.stats.plans[1].selections[0].targetVersion === "2.0.0"', 'detail update used the detail version instead of the latest eligible one')
  })

  await check('组合：首页私有入口、自动预检和未勾试装的部分执行', async () => {
    await render('collection-home')
    const home = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
    writeFileSync(join(output, 'collection-home-1280.png'), Buffer.from(home.data, 'base64'))
    await click('查看组合变更'); await until('fixture.stats.plans.length === 1')
    await expect('fixture.stats.plans[0].collectionId === "collection-test" && fixture.stats.plans[0].collectionVersion === "2.0.0" && !("packId" in fixture.stats.plans[0]) && fixture.stats.plans[0].selections.every(item => item.tryUnverified === false && item.enabledIntent === false)', 'private collection did not preserve its request identity')
    await expect('document.body.innerText.includes("可执行 1 项") && document.body.innerText.includes("跳过 2 项") && document.body.innerText.includes("依赖暂停 1 项")', 'partial scope is not explicit')
    await click('确认执行可用项'); await expect('fixture.stats.starts.length === 1 && document.body.innerText.includes("部分完成")', 'safe subset was blocked or result falsely shown complete')
  })
  await check('组合：上游验证状态不增加安装门槛，硬阻断仍明确跳过', async () => {
    await render('collection-consent'); await click('查看组合变更'); await until('fixture.stats.plans.length === 1')
    await expect('!document.querySelector("input[type=checkbox]") && fixture.stats.plans[0].selections.every(item => item.tryUnverified === false) && document.body.innerText.includes("可执行 3 项") && document.body.innerText.includes("跳过 1 项")', 'native-like collection install still demanded consent')
    await send('Emulation.setDeviceMetricsOverride', { width: 480, height: 900, deviceScaleFactor: 1, mobile: false })
    await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'collection preflight overflows at 480px')
    const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
    writeFileSync(join(output, 'collection-plan-480.png'), Buffer.from(shot.data, 'base64'))
  })
  await check('组合：公共Pack部分阻止仍允许安全项，身份不混成collection', async () => {
    await render('pack-partial'); await click('查看套餐变更'); await until('fixture.stats.plans.length === 1')
    await expect('fixture.stats.plans[0].packId === "pack-test" && !("collectionId" in fixture.stats.plans[0]) && document.body.innerText.includes("依赖暂停 1 项")', 'public Pack identity or dependency scope changed')
    await click('确认执行可用项'); await expect('fixture.stats.starts.length === 1', 'partial Pack could not start')
  })
  await check('组合：整套blocked与不安全Host计划都禁止确认', async () => {
    for (const mode of ['collection-all-blocked', 'collection-unsafe']) {
      await render(mode); await click('查看组合变更'); await until('fixture.stats.plans.length === 1')
      await expect("fixture.stats.starts.length === 0 && [...document.querySelectorAll('button')].find(el => el.textContent === '确认执行可用项').disabled", mode + ' was not blocked')
    }
  })
  await check('组合：内容摘要漂移拒绝旧确认', async () => {
    await render('collection-stale'); await click('查看组合变更'); await until('fixture.stats.plans.length === 1')
    await expect("document.body.innerText.includes('组合版本或内容已变化') && fixture.stats.starts.length === 0 && [...document.querySelectorAll('button')].find(el => el.textContent === '确认执行可用项').disabled", 'changed collection reused old confirmation')
  })

  await check('安装只需一次最终确认，不再要求额外试装勾选', async () => {
    await render('install'); await click('打开安装窗口'); await until('fixture.stats.plans.length === 1')
    await expect("!document.querySelector('input[type=checkbox]') && ![...document.querySelectorAll('button')].find(e=>e.textContent==='确认安装').disabled", 'native-like install still demanded an extra checkbox')
    await click('确认安装'); await until('fixture.stats.starts.length === 1')
    await expect('fixture.stats.plans.length === 1', 'install preflight was unnecessarily replayed')
  })
  await check('A迟到成功不能关闭B或串用B计划', async () => {
    await render('late'); await click('打开安装窗口'); await until('fixture.stats.plans.length === 1')
    await click('确认安装')
    await evaluate('fixture.openB()'); await until('document.body.innerText.includes("安装确认：合成插件 B")'); await evaluate('fixture.resolveA()'); await pause(100)
    await expect('fixture.stats.closes === 0 && fixture.stats.started[0] === "A" && document.body.innerText.includes("安装确认：合成插件 B")', 'late A closed B')
  })
  await check('降级第一次确认零写，第二次确认才提交', async () => {
    await render('downgrade'); await click('打开安装窗口'); await until('fixture.stats.plans.length === 1'); await until("([...document.querySelectorAll('button')].some(b => b.textContent.trim()==='查看降级影响' && !b.disabled))"); await click('查看降级影响')
    await expect('fixture.stats.starts.length === 0 && document.body.innerText.includes("再次确认降级影响")', 'downgrade wrote before impact')
    await click('已了解影响，确认降级'); await expect('fixture.stats.starts.length === 1', 'downgrade second confirmation did not submit')
  })
  await check('AI按任务展示，危险动作首确认无risk字段，第二确认带challenge', async () => {
    await render('ai'); await click('AI 分析本任务', 'document.querySelector(\'[aria-label="任务 A"]\')')
    await until('document.body.innerText.includes("只属于 A 的方案")')
    await expect('!document.querySelector(\'[aria-label="任务 B"]\').textContent.includes("只属于 A")', 'AI proposal leaked into task B')
    await click('确认执行 AI 方案'); await until('fixture.stats.ai.length === 1')
    await expect('!("riskConfirmed" in fixture.stats.ai[0]) && !("challengeId" in fixture.stats.ai[0])', 'first confirmation carried risk consent')
    await click('已了解影响，再次确认执行')
    await expect('fixture.stats.ai[1].riskConfirmed === true && fixture.stats.ai[1].challengeId === "challenge" && fixture.stats.ai[1].challengeDigest === "challenge-digest"', 'second confirmation lacks bound challenge')
  })
  await check('AI queued读取真实任务并并入列表，不显示applied', async () => {
    await render('ai-queued'); await click('AI 分析本任务', 'document.querySelector(\'[aria-label="任务 A"]\')')
    await until('document.body.innerText.includes("只属于 A 的方案")'); await click('确认执行 AI 方案')
    await expect('fixture.stats.started.includes("ai-queued-task") && document.body.innerText.includes("任务已排队") && !document.body.innerText.includes("操作已执行")', 'queued shown as applied or task not merged')
  })
  await check('作者草稿重开、README差异、冲突保留原稿与出站API调用', async () => {
    await render('author'); await click('合成草稿' + await evaluate('document.querySelector(".eac-market__draft-list small").textContent'))
    await until('document.getElementById("draft-markdown").value === "旧正文"')
    await input('repo-url', 'https://github.com/example/test'); await click('读取并预览差异')
    await until('document.body.innerText.includes("确认正文差异")')
    await expect('fixture.stats.saved.length === 0', 'README preview overwrote draft')
    await evaluate('fixture.conflict()'); await click('确认差异并保存')
    await expect('document.body.innerText.includes("revision 已变化") && document.getElementById("draft-markdown").value === "旧正文"', 'conflict lost original')
    await click('关闭'); await click('保存并导出介绍 ZIP')
    await expect('fixture.stats.exports === 1 && fixture.stats.dispose === 1', 'ZIP did not use outbound API')
  })
  await check('作者图片上传绑定草稿revision，校验预览并插入正文', async () => {
    await render('author'); await click('合成草稿' + await evaluate('document.querySelector(".eac-market__draft-list small").textContent'))
    const photo = join(output, 'test-media.png')
    writeFileSync(photo, Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64'))
    const doc = await send('DOM.getDocument')
    const field = await send('DOM.querySelector', { nodeId: doc.root.nodeId, selector: '#draft-image' })
    await send('DOM.setFileInputFiles', { nodeId: field.nodeId, files: [photo] })
    await until('!!document.querySelector(".eac-market__media-list img")')
    await expect('fixture.stats.mediaUploads[0].targetId === "draft-one" && fixture.stats.mediaUploads[0].expectedRevision === "r1"', 'media upload is not bound')
    await click('插入正文'); await expect('document.getElementById("draft-markdown").value.includes("media://img-fixture")', 'media not inserted')
  })
  await check('普通卸载实际两次确认且官方导航可调用', async () => {
    await render('remove'); await click('我的插件'); await click('打开官方插件页'); await expect('fixture.stats.official > 0', 'official navigation not wired')
    await click('卸载'); await click('继续查看卸载影响'); await expect('fixture.stats.started.length === 0', 'remove first confirm wrote')
    await click('已了解影响，再次确认卸载'); await expect('fixture.stats.started.includes("remove")', 'second confirmation did not remove')
  })
  await check('目录刷新失败显示原因，不报已刷新', async () => {
    await render('home'); await click('更多'); await click('设置'); await click('刷新目录')
    await expect('document.body.innerText.includes("目录刷新失败") && document.body.innerText.includes("为避免泄露本机路径或来源凭据") && !document.body.innerText.includes("目录已刷新。") && !document.body.innerText.includes("合成来源离线")', 'refresh failure state or safe error guidance was lost')
  })
  await check('任务记录：按需读取完整历史并分段加载', async () => {
    await render('task-events')
    await until('!!document.querySelector(".eac-market__task-history summary")')
    await evaluate('document.querySelector(".eac-market__task-history summary").click()')
    await until('fixture.stats.taskEventReads === 1 && document.body.innerText.includes("合成历史事件 100")')
    await expect('fixture.stats.taskEventOffsets[0] === -1 && document.body.innerText.includes("合成历史事件 1")', 'first event page did not include sequence zero')
    await expect('[...document.querySelectorAll(".eac-market__task button")].some(button => button.textContent.includes("加载更多记录"))', 'task event pagination control missing')
    await click('加载更多记录'); await until('fixture.stats.taskEventReads === 2 && document.body.innerText.includes("合成历史事件 130")')
    await expect('fixture.stats.taskEventOffsets[1] === 99 && document.body.innerText.includes("合成历史事件 101")', 'second event page skipped or repeated a sequence')
    await expect('![...document.querySelectorAll(".eac-market__task button")].some(button => button.textContent.includes("加载更多记录"))', 'task event pagination did not finish')
  })
  await check('任务记录：兼容旧 Host 返回全历史末端游标，不跳过未读页', async () => {
    await render('task-events-legacy-cursor')
    await until('!!document.querySelector(".eac-market__task-history summary")')
    await evaluate('document.querySelector(".eac-market__task-history summary").click()')
    await until('fixture.stats.taskEventReads === 1 && document.body.innerText.includes("合成历史事件 100")')
    await click('加载更多记录')
    await until('fixture.stats.taskEventReads === 2 && document.body.innerText.includes("合成历史事件 130")')
    await expect('fixture.stats.taskEventOffsets[1] === 99 && document.body.innerText.includes("合成历史事件 101")', 'legacy tail cursor skipped unread event history')
  })
  await check('任务记录：截断/读取失败明确提示，保留任务摘要', async () => {
    await render('task-events-truncated')
    await until('!!document.querySelector(".eac-market__task-history summary")')
    await evaluate('document.querySelector(".eac-market__task-history summary").click()')
    await until('document.body.innerText.includes("部分历史记录已被清理或不完整")')
    await render('task-events-failure')
    await until('!!document.querySelector(".eac-market__task-history summary")')
    await evaluate('document.querySelector(".eac-market__task-history summary").click()')
    await until('document.body.innerText.includes("完整记录读取失败")')
    await expect('document.body.innerText.includes("开始安装 @example/alpha") && [...document.querySelectorAll("button")].some(button => button.textContent.includes("重新读取任务记录"))', 'history failure removed recent summary or prevented manual read recovery')
  })
  await check('任务记录：旧 Host 缺少 taskEvents 时保留最近摘要并明确说明', async () => {
    await render('task-events-no-api')
    await until('!!document.querySelector(".eac-market__task-history summary")')
    await evaluate('document.querySelector(".eac-market__task-history summary").click()')
    await until('document.body.innerText.includes("当前宿主不支持读取完整历史")')
    await expect('document.body.innerText.includes("开始安装 @example/alpha")', 'legacy task fallback did not show the current summary events')
    await expect('![...document.querySelectorAll(".eac-market__task button")].some(button => button.textContent.includes("加载更多记录"))', 'legacy task fallback exposed an unsupported pagination action')
  })
  await check('设置：来源受控刷新、只读版本检查和当前环境维护状态', async () => {
    await render('settings'); await click('更多'); await click('设置')
    await until('document.body.innerText.includes("已配置的来源") && document.body.innerText.includes("运行状态")')
    await expect('document.body.innerText.includes("Agent Forge来源") && document.body.innerText.includes("离线内容需要通过独立导入流程更新")', 'configured source types or offline boundary are missing')
    await expect('(() => { const row=[...document.querySelectorAll(".eac-market__source-row")].find(item => item.textContent.includes("离线内容需要通过独立导入流程更新")); return !!row && !row.querySelector("button") })()', 'offline-pack source exposed an unsupported refresh control')
    await expect('!document.body.innerText.includes("fixture-token") && !document.body.innerText.includes("fixture-private") && !document.body.innerText.includes("fixture-user")', 'raw backend source error leaked credentials or a local path')
    await expect('document.body.innerText.includes("1 个任务进行中") && document.body.innerText.includes("有操作等待重启")', 'maintenance snapshot was not surfaced')
    await expect('!document.body.innerText.includes("https://example.invalid") && !document.body.innerText.includes("C:" + String.fromCharCode(92)) && !document.querySelector("input[name=sourceUrl]")', 'source URL or local path leaked into Client')
    await click('刷新此来源'); await until('fixture.stats.sourceRefreshes.length === 1')
    await until('document.body.innerText.includes("来源已刷新，市场目录已同步")')
    await expect('fixture.stats.sourceRefreshes[0] === "curated-main"', 'refresh did not target the registered source ID')
    await until('document.querySelector(".eac-market__source-row .eac-market__source-title")?.textContent.includes("可用")')
    await click('检查当前目录'); await until('fixture.stats.updateChecks === 1')
    await until('document.body.innerText.includes("目录已过期或刷新状态不确定")')
    await expect('document.body.innerText.includes("发现新版本") && document.body.innerText.includes("无法确认") && document.body.innerText.includes("不下载、不安装")', 'manual update result lost stale/unknown/read-only semantics')
  })
  await check('设置：读取偏好、保存只读检查策略并保留自动写入关闭', async () => {
    await render('settings'); await click('更多'); await click('设置')
    await until('document.querySelector(".eac-market__policy-toggle input") && document.body.innerText.includes("当前接口尚不能显示调度是否已启动")')
    await evaluate('document.querySelector(".eac-market__policy-toggle input").click()')
    await click('保存偏好'); await until('fixture.stats.policyWrites.length === 1')
    await until('document.body.innerText.includes("检查偏好已保存")')
    await expect('fixture.stats.policyWrites[0].expectedRevision === "policy:r1" && fixture.stats.policyWrites[0].policy.automaticChecksEnabled === false && fixture.stats.policyWrites[0].policy.automaticDownloadsEnabled === false && fixture.stats.policyWrites[0].policy.automaticInstallsEnabled === false', 'saved policy did not use revision or read-only limits')
    await expect('document.querySelector(".eac-market__policy-toggle input").checked === false', 'saved policy was not reflected in the control')
  })
  await check('设置：连续调整开关与周期保存正确值，不读取已释放的事件对象', async () => {
    await render('settings'); await click('更多'); await click('设置')
    await until('!!document.querySelector(".eac-market__policy-editor select")')
    await expect('!document.body.innerText.includes("当前宿主尚未提供版本检查能力") && fixture.stats.updateChecks === 0', 'available update check was mislabeled as unavailable before the first read')
    await evaluate('(() => { const toggle=document.querySelector(".eac-market__policy-toggle input"); const select=document.querySelector(".eac-market__policy-editor select"); toggle.click(); select.value="180"; select.dispatchEvent(new Event("change",{bubbles:true})); })()')
    await until('document.querySelector(".eac-market__policy-toggle input")?.checked === false && document.querySelector(".eac-market__policy-editor select")?.value === "180"')
    await click('保存偏好'); await until('fixture.stats.policyWrites.length === 1')
    await expect('fixture.stats.policyWrites[0].policy.automaticChecksEnabled === false && fixture.stats.policyWrites[0].policy.intervalMinutes === 180', 'combined policy edits were lost')
  })
  await check('设置：如实显示旧偏好的自动写入项，用户保存才关闭', async () => {
    await render('settings-unsafe-policy'); await click('更多'); await click('设置')
    await until('document.body.innerText.includes("自动下载开启") && document.body.innerText.includes("自动安装开启")')
    await expect('fixture.stats.policyWrites.length === 0 && fixture.stats.starts.length === 0', 'reading a legacy policy silently wrote preferences or started a task')
    await click('保存偏好'); await until('fixture.stats.policyWrites.length === 1 && document.body.innerText.includes("自动下载关闭") && document.body.innerText.includes("自动安装关闭")')
    await expect('fixture.stats.policyWrites[0].policy.automaticDownloadsEnabled === false && fixture.stats.policyWrites[0].policy.automaticInstallsEnabled === false && fixture.stats.starts.length === 0', 'policy save enabled automatic writes')
  })
  await check('设置：revision 冲突后重读当前值、保留用户草稿且不自动覆盖', async () => {
    await render('settings-conflict'); await click('更多'); await click('设置')
    await until('!!document.querySelector(".eac-market__policy-toggle input")')
    await clickSelector('.eac-market__policy-toggle input')
    await until('!!document.querySelector(".eac-market__policy-toggle input") && document.querySelector(".eac-market__policy-toggle input").checked === false')
    await until('[...document.querySelectorAll("button")].some(button => button.textContent.includes("保存偏好") && !button.disabled)')
    await click('保存偏好'); await until('fixture.stats.policyWrites.length === 1 && fixture.stats.policyReads >= 2')
    await until('document.body.innerText.includes("旧值不会被自动覆盖")')
    await expect('document.querySelector(".eac-market__policy-toggle input").checked === false && [...document.querySelectorAll("button")].some(button => button.textContent.includes("保存偏好") && !button.disabled)', 'conflict reload discarded the unsaved user choice')
    await expect('fixture.stats.policyWrites.length === 1', 'conflict was automatically retried')
  })
  await check('设置：来源刷新失败不泄露后台 URL/凭据/本机路径', async () => {
    await render('settings-refresh-failure'); await click('更多'); await click('设置')
    await until('document.body.innerText.includes("已配置的来源")')
    await click('刷新此来源'); await until('document.body.innerText.includes("为避免泄露本机路径或来源凭据")')
    await expect('!document.body.innerText.includes("fixture-token") && !document.body.innerText.includes("fixture-private") && !document.body.innerText.includes("fixture-user")', 'raw backend refresh failure leaked sensitive source details')
  })
  await check('设置：拒绝展示属于其他 Profile 的维护状态', async () => {
    await render('settings-foreign-environment'); await click('更多'); await click('设置')
    await until('document.body.innerText.includes("后台返回的状态不属于当前环境，已拒绝展示")')
    await expect('!document.body.innerText.includes("已核对 1 项插件状态") && !document.body.innerText.includes("1 个任务进行中")', 'foreign profile maintenance details leaked into the current market')
  })
  await check('设置：能力声明缺失时不调用后端新接口', async () => {
    await render('settings-capability-missing'); await click('更多'); await click('设置')
    await until('document.body.innerText.includes("当前宿主版本未提供来源列表") && document.body.innerText.includes("当前宿主版本未提供维护状态接口") && document.body.innerText.includes("当前宿主尚未提供版本检查能力")')
    await expect('!document.body.innerText.includes("Agent Forge来源") && fixture.stats.policyReads === 0 && fixture.stats.updateChecks === 0 && fixture.stats.maintenanceReads === 0', 'capability negotiation did not prevent unsupported backend calls')
  })
  await check('设置：旧宿主缺少新接口时明确降级', async () => {
    await render('home'); await click('更多'); await click('设置')
    await until('document.body.innerText.includes("当前宿主版本未提供来源列表") && document.body.innerText.includes("当前宿主版本未提供维护状态接口") && document.body.innerText.includes("当前宿主尚未提供版本检查能力")')
    await expect('![...document.querySelectorAll("button")].some(button => button.textContent.includes("刷新此来源")) && !document.body.innerText.includes("后台定时调度尚未接入")', 'old-host fallback exposed an unusable or misleading control')
  })
  await check('设置：480px/1280px 面板均可用，交互控件不溢出且保持触达尺寸', async () => {
    for (const width of [480, 1280]) {
      await send('Emulation.setDeviceMetricsOverride', { width, height: 900, deviceScaleFactor: 1, mobile: false })
      await render('settings'); await click('更多'); await click('设置')
      await until('document.body.innerText.includes("已配置的来源") && !!document.querySelector(".eac-market__policy-toggle input")')
      await until('[...document.querySelectorAll(".eac-market__source-row button")].some(button => button.textContent.includes("刷新此来源") && !button.disabled) && [...document.querySelectorAll("button")].some(button => button.textContent.includes("检查当前目录") && !button.disabled)')
      await evaluate(`document.documentElement.style.cssText=${JSON.stringify(width === 480 ? '--dsw-alias-bg-base:#141414;--dsw-alias-bg-layer-1:#232323;--dsw-alias-bg-layer-2:#303030;--dsw-alias-label-primary:#eeeeee;--dsw-alias-label-secondary:#b8b8b8;--dsw-alias-label-tertiary:#aaaaaa;--dsw-alias-border-l1:#4a4a4a;--dsw-alias-border-l3:#666666;--dsw-alias-link:#8aafff;--dsw-alias-state-business-primary:#386ad9;' : '')}`)
      await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'settings viewport overflow')
      const controlSizes = await evaluate('JSON.stringify({refresh: document.querySelector(".eac-market__source-row .eac-button:not(:disabled)")?.getBoundingClientRect().height, interval: document.querySelector(".eac-market__policy-editor select")?.getBoundingClientRect().height, viewport: innerWidth, document: document.documentElement.scrollWidth})')
      const parsedSizes = JSON.parse(controlSizes)
      if (parsedSizes.refresh < 44 || parsedSizes.interval < 44) throw new Error('settings controls are below 44px at ' + width + 'px: ' + controlSizes)
      const buttonContrast = await evaluate('(() => { const button=document.querySelector(".eac-market__source-row .eac-button:not(:disabled)"); const rgb=value=>value.match(/[\\d.]+/g).slice(0,3).map(Number); const lum=value=>rgb(value).map(channel=>{const c=channel/255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4}).reduce((total,channel,index)=>total+channel*[.2126,.7152,.0722][index],0); const style=getComputedStyle(button); const values=[lum(style.color),lum(style.backgroundColor)].sort((a,b)=>b-a); return (values[0]+.05)/(values[1]+.05) })()')
      if (buttonContrast < 4.5) throw new Error('enabled source action contrast is below 4.5:1 at ' + width + 'px: ' + buttonContrast)
      await evaluate('document.querySelector(".eac-market__scroll").scrollTo({top:0, behavior:"instant"})')
      const settingsCapture = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true })
      writeFileSync(join(output, width === 480 ? 'settings-480-dark.png' : 'settings-1280-light.png'), Buffer.from(settingsCapture.data, 'base64'))
    }
  })
  await check('键盘Tab困于对话框、Escape关闭、焦点返回触发按钮', async () => {
    await render('install'); await evaluate('document.getElementById("launch").focus()'); await click('打开安装窗口')
    await until('!!document.querySelector("[role=dialog]")')
    await evaluate("(() => { const a=[...document.querySelector('[role=dialog]').querySelectorAll('button:not([disabled]),input:not([disabled])')]; a[a.length-1].focus() })()")
    await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9 }); await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Tab', code: 'Tab', windowsVirtualKeyCode: 9 })
    await expect("document.querySelector('[role=dialog]').contains(document.activeElement)", 'Tab escaped dialog')
    await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 }); await pause(50)
    await expect('!document.querySelector("[role=dialog]") && document.activeElement.id === "launch"', 'Escape focus did not return')
  })
  await check('更多菜单支持方向键和Escape焦点恢复', async () => {
    await render('home'); await click('更多')
    await expect('document.activeElement.textContent === "设置"', 'menu did not focus first item')
    await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'ArrowDown', code: 'ArrowDown', windowsVirtualKeyCode: 40 })
    await expect('document.activeElement.textContent === "作者工具"', 'menu ArrowDown did not navigate')
    await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 }); await pause(40)
    await expect('!document.querySelector("[role=menu]") && document.activeElement.textContent === "更多"', 'menu Escape did not return focus')
  })

  if (listingsOnly) {
    await check('登记：27条默认折叠，位于主列表之后，不混入功能卡片', async () => {
      await render('skins-listings'); await click('全部插件')
      await expect('!document.querySelector(".eac-market__pending-listings")', 'research-only records leaked into default installable view')
      await click('全部记录')
      await expect('document.querySelector(".eac-market__pending-listings") && !document.querySelector(".eac-market__pending-listings").open && document.querySelectorAll(".eac-market__pending-list li").length === 27', 'registered catalog not collapsed or incomplete')
      await expect('document.querySelectorAll(".eac-market__plugin-card").length === 1 && document.querySelector(".eac-market__pending-listings").getBoundingClientRect().top > document.querySelector(".eac-market__plugin-card").getBoundingClientRect().top', 'listings displaced plugin grid')
      await evaluate('document.querySelector(".eac-market__pending-listings summary").click()')
      await expect('document.querySelectorAll(".eac-market__pending-list button").length === 0 && document.querySelectorAll(".eac-market__pending-list a").length === 27 && skinFixture.stats.plans.length === 0 && skinFixture.stats.starts.length === 0', 'registration row exposes install action')
    })
    await check('登记：名称/说明搜索，申请版本标为未核实，无结果可恢复', async () => {
      await input('eac-market-search', '语音整理')
      await expect('document.querySelectorAll(".eac-market__pending-list li").length === 1 && document.querySelector(".eac-market__pending-list").textContent.includes("合成登记功能 6")', 'description search failed')
      await input('eac-market-search', '合成登记功能 2')
      await expect('document.querySelector(".eac-market__pending-list").textContent.includes("申请版本：2.0.0（未核实）")', 'requested version presented as verified release')
      await input('eac-market-search', '找不到的记录')
      await expect('document.querySelector(".eac-market__pending-listings").textContent.includes("没有匹配的登记项目")', 'empty search unexplained')
      await input('eac-market-search', '')
      await expect('document.querySelectorAll(".eac-market__pending-list li").length === 27', 'clearing search did not restore records')
    })
    for (const [width, dark] of [[1280, false], [480, true]]) {
      await check(`登记：${width}px展开收起、窄面板无横向溢出`, async () => {
        await send('Emulation.setDeviceMetricsOverride', { width, height: 760, deviceScaleFactor: 1, mobile: false }); await theme(dark)
        await render('skins-listings'); await click('全部插件'); await click('全部记录')
        await evaluate('document.querySelector(".eac-market__pending-listings summary").scrollIntoView({block:"center"})')
        let shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); writeFileSync(join(output, `pending-collapsed-${width}.png`), Buffer.from(shot.data, 'base64'))
        await evaluate('document.querySelector(".eac-market__pending-listings summary").click();document.querySelector(".eac-market__pending-listings summary").scrollIntoView({block:"start"});document.querySelector(".eac-market__scroll").scrollTop -= document.querySelector(".eac-market__topbar").getBoundingClientRect().height + 12')
        await expect('document.documentElement.scrollWidth <= innerWidth + 1 && document.querySelector(".eac-market__pending-listings").open', 'expanded pending catalog overflows')
        shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); writeFileSync(join(output, `pending-expanded-${width}.png`), Buffer.from(shot.data, 'base64'))
        await evaluate('document.querySelector(".eac-market__pending-listings summary").click()')
        await expect('!document.querySelector(".eac-market__pending-listings").open', 'cannot collapse listing')
      })
    }
  }
  if (skinsOnly) {
    const skinScope = (index) => `[...document.querySelectorAll('.eac-market__plugin-card')].find(e => e.querySelector('h3').textContent === '合成皮肤 ${index}')`
    const installedScope = (index) => `[...document.querySelectorAll('.eac-market__skin-installed')].find(e => e.querySelector('h3').textContent === '合成皮肤 ${index}')`
    const center = async (mode = 'skins-installed') => { await render(mode); await click('打开皮肤中心'); await until('document.querySelector("h1").textContent === "皮肤中心"') }
    await check('皮肤：三主导航、首页全部排除单独皮肤和重复loader卡', async () => {
      await render('skins-catalog')
      await expect('document.querySelectorAll(".eac-market__nav button").length === 3 && document.querySelectorAll("[aria-label=皮肤管理器入口]").length === 1', 'entry or nav count wrong')
      await expect('![...document.querySelectorAll(".eac-market__plugin-card h3")].some(e => e.textContent.startsWith("合成皮肤"))', 'skin recommendations leaked into discovery')
      await click('全部插件')
      await expect('document.querySelectorAll(".eac-market__plugin-card").length === 1 && document.body.innerText.includes("合成功能插件")', 'classification guessed from package prefix or loader duplicated')
      await click('我的插件'); await expect('document.body.innerText.includes("0 款已安装")', 'catalog marked installed')
    })
    await check('皮肤：catalog-only浏览搜索与缺制品/暂停保留', async () => {
      await center('skins-catalog')
      await expect('document.querySelectorAll(".eac-market__skin-center .eac-market__plugin-card").length === 13 && document.body.innerText.includes("尚未安装")', 'skin count or missing runtime guidance wrong')
      await expect('!document.body.innerText.includes("已恢复默认") && ![...document.querySelectorAll("button")].some(e => e.textContent === "恢复默认外观")', 'invented current skin or switch action')
      await input('eac-skin-search', '合成皮肤 10')
      await expect('document.querySelectorAll(".eac-market__skin-center .eac-market__plugin-card").length === 1 && document.body.innerText.includes("缺少可下载制品")', 'missing artifact skin hidden')
      await input('eac-skin-search', '合成皮肤 11')
      await expect('document.body.innerText.includes("安装已阻止") && document.body.innerText.includes("兼容修复")', 'blocked reason hidden')
      await click('查看详情', skinScope(11)); await click('返回皮肤中心')
      await expect('document.getElementById("eac-skin-search").value === "合成皮肤 11"', 'search lost on detail return')
    })
    await check('皮肤：先引导loader、核心完整计划、确认前零写', async () => {
      await center('skins-catalog'); await click('查看安装方案', skinScope(0))
      await expect('skinFixture.stats.plans.length === 0 && skinFixture.stats.starts.length === 0', 'guide performed a write')
      await click('先查看管理器安装方案'); await until('skinFixture.stats.plans.length === 1')
      await expect('skinFixture.stats.plans[0].selections.length === 1 && skinFixture.stats.plans[0].selections[0].packageName === "@dsh-eac/ui-skin-loader" && skinFixture.stats.starts.length === 0', 'loader auto installed or skin added to plan')
      await click('关闭'); await click('查看安装方案', skinScope(0)); await click('仅查看此皮肤安装方案'); await until('skinFixture.stats.plans.length === 2')
      await expect('skinFixture.stats.plans[1].selections[0].packageName === "@test/appearance-0" && skinFixture.stats.starts.length === 0', 'skin selection or confirmation gate wrong')
      await click('确认安装'); await until('skinFixture.stats.starts.length === 1')
      await expect('skinFixture.stats.switches.length === 0', 'install automatically switched skin')
    })
    await check('皮肤：已安装聚合、loader仍为功能、停用/故障/版本保留', async () => {
      await render('skins-installed'); await click('我的插件')
      await expect('document.body.innerText.includes("3 款已安装") && !document.body.innerText.includes("合成皮肤 0") && document.body.innerText.includes("合成皮肤管理器")', 'inventory aggregation lost loader or leaked skins')
      await click('打开皮肤中心'); await click('已安装皮肤（3）')
      await expect('document.querySelectorAll(".eac-market__skin-installed").length === 3 && document.body.innerText.includes("已登记，未使用") && document.body.innerText.includes("激活故障") && document.body.innerText.includes("已停用") && document.body.innerText.includes("1.0.0")', 'installed facts lost')
      await expect(`${installedScope(2)}.querySelector('.eac-market__skin-controls button').disabled`, 'disabled skin switch available')
      await click('使用此皮肤', installedScope(0)); await until('document.body.innerText.includes("加载器已确认使用此皮肤")')
      await expect('skinFixture.stats.switches[0] === "test-skin-0" && document.body.innerText.includes("合成皮肤 0 · 1.0.0 · 使用中")', 'active state not tied to current/status')
      await click('恢复默认外观'); await until('document.body.innerText.includes("已恢复默认外观")')
      await expect('skinFixture.stats.switches[1] === "default"', 'default target incorrect')
    })
    await check('皮肤：失败/回退与未确认响应不假报成功，故障重试需确认', async () => {
      await center(); await click('已安装皮肤（3）'); await evaluate('skinFixture.behavior("unconfirmed")')
      await click('使用此皮肤', installedScope(0)); await until('document.body.innerText.includes("未确认目标生效")')
      await expect('!document.body.innerText.includes("加载器已确认使用此皮肤")', 'ok response used as active evidence')
      await evaluate('skinFixture.behavior("fail")'); await click('查看重试说明', installedScope(1))
      await expect('skinFixture.stats.switches.length === 1', 'fault retry happened without confirmation')
      await click('确认重试此皮肤', installedScope(1)); await until('document.body.innerText.includes("合成激活故障")')
      await expect('document.body.innerText.includes("回退到 默认外观") && document.body.innerText.includes("合成残留提醒")', 'rollback or warning lost')
    })
    await check('皮肤：服务移除清理监听并拒绝迟到成功，重新出现可恢复', async () => {
      await center('skins-offline'); await click('已安装皮肤（3）')
      await expect('!document.body.innerText.includes("使用此皮肤") && document.body.innerText.includes("切换服务暂不可用")', 'offline exposes switch')
      await evaluate('skinFixture.availability(true)'); await until('skinFixture.stats.runtimeListeners === 1')
      await evaluate('skinFixture.behavior("late")'); await click('使用此皮肤', installedScope(0))
      await evaluate('skinFixture.availability(false)'); await until('skinFixture.stats.runtimeListeners === 0')
      await evaluate('skinFixture.settle()'); await pause(60)
      await expect('!document.body.innerText.includes("加载器已确认使用此皮肤") && !document.body.innerText.includes("使用此皮肤")', 'stale result survived service removal')
      await evaluate('skinFixture.availability(true)'); await until('skinFixture.stats.runtimeListeners === 1')
      await render('skins-catalog'); await until('skinFixture.stats.runtimeListeners === 0 && skinFixture.stats.bridgeListeners === 0')
    })
    await check('皮肤：仅服务登记/幽灵active不能冒充已安装或切换成功', async () => {
      await center('skins-ghost'); await evaluate('skinFixture.ghost()')
      await expect('document.body.innerText.includes("已安装皮肤（0）") && document.body.innerText.includes("尚未确认当前外观") && !document.body.innerText.includes("使用此皮肤")', 'registration treated as installation/activation')
    })
    await check('皮肤：同一轮移除再提供服务不会卡住busy或接纳旧结果', async () => {
      await center(); await click('已安装皮肤（3）'); await evaluate('skinFixture.behavior("late")')
      await click('使用此皮肤', installedScope(0))
      await evaluate('skinFixture.availability(false); skinFixture.availability(true)')
      await until('!document.body.innerText.includes("正在等待皮肤管理器完成切换")')
      await evaluate('skinFixture.settle()'); await pause(60)
      await expect('!document.body.innerText.includes("加载器已确认使用此皮肤") && skinFixture.stats.runtimeListeners === 1', 'batched lifetime change left stale state')
      await evaluate('skinFixture.behavior("throw")'); await click('使用此皮肤', installedScope(0)); await until('document.body.innerText.includes("合成连接中断")')
      await expect('!document.body.innerText.includes("加载器已确认使用此皮肤")', 'exception reported success')
    })
    for (const [width, dark] of [[1280, false], [480, true]]) {
      await check(`皮肤：${width}px布局/滚动/截图`, async () => {
        await send('Emulation.setDeviceMetricsOverride', { width, height: 760, deviceScaleFactor: 1, mobile: false }); await theme(dark)
        await render('skins-catalog')
        let shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); writeFileSync(join(output, `skin-entry-${width}.png`), Buffer.from(shot.data, 'base64'))
        await click('打开皮肤中心')
        await expect('document.documentElement.scrollWidth <= innerWidth + 1 && document.querySelector(".eac-market-host").getBoundingClientRect().bottom <= innerHeight + 1', 'skin page overflows official panel')
        shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); writeFileSync(join(output, `skin-browse-${width}.png`), Buffer.from(shot.data, 'base64'))
        await send('Input.dispatchMouseEvent', { type: 'mouseWheel', x: width - 60, y: 500, deltaY: 700, deltaX: 0 }); await until('document.querySelector(".eac-market__scroll").scrollTop > 100')
        await center(); await click('已安装皮肤（3）'); await evaluate('document.querySelector(".eac-market__scroll").scrollTo(0,0)')
        shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); writeFileSync(join(output, `skin-installed-${width}.png`), Buffer.from(shot.data, 'base64'))
      })
    }
  }
  for (const [width, dark] of [[1280, false], [480, true]]) {
    await check(`滚动：官方受限面板 ${width}px 的折叠、滚轮与键盘`, async () => {
      await send('Emulation.setDeviceMetricsOverride', { width, height: 760, deviceScaleFactor: 1, mobile: false })
      await theme(dark); await render('inventory-scroll'); await click('我的插件')
      await until('document.querySelector(".eac-market__system-group") !== null')
      await expect('!document.querySelector(".eac-market__system-group").open && !document.querySelector(".eac-market__system-group .eac-market__grid").children.length', 'official group should start closed without hidden card work')
      await expect('document.querySelector(".eac-market__system-group summary").textContent.includes("28") && document.querySelector(".eac-market__group-warning").textContent.includes("2")', 'collapsed summary loses the official count or warning')
      await evaluate('document.querySelector(".eac-market__system-group summary").click()')
      await until('document.querySelector(".eac-market__system-group .eac-market__grid").children.length === 28')
      await expect('document.querySelector(".eac-market__scroll").scrollHeight > document.querySelector(".eac-market__scroll").clientHeight && document.querySelector(".eac-market-host").getBoundingClientRect().bottom <= innerHeight + 1', 'list grows out of the official clipped panel')
      await send('Input.dispatchMouseEvent', { type: 'mouseWheel', x: width - 60, y: 500, deltaY: 700, deltaX: 0 })
      await until('document.querySelector(".eac-market__scroll").scrollTop > 100')
      await evaluate('document.querySelector(".eac-market__scroll").focus()')
      await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'End', code: 'End', windowsVirtualKeyCode: 35 })
      await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'End', code: 'End', windowsVirtualKeyCode: 35 })
      await until('Math.abs(document.querySelector(".eac-market__scroll").scrollHeight - document.querySelector(".eac-market__scroll").clientHeight - document.querySelector(".eac-market__scroll").scrollTop) < 5')
      await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'narrow grouped list overflows horizontally')
      await evaluate('document.querySelector(".eac-market__system-group summary").click()')
      await until('!document.querySelector(".eac-market__system-group").open')
      await evaluate('document.querySelector(".eac-market__scroll").scrollTo(0,0)')
      const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
      writeFileSync(join(output, `mine-collapsed-${width}.png`), Buffer.from(shot.data, 'base64'))
    })
  }
  if (compatibilityOnly) {
    await check('兼容：forced-colors 与 reduced-motion', async () => {
      await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
      await send('Emulation.setEmulatedMedia', { features: [{ name: 'forced-colors', value: 'active' }, { name: 'prefers-reduced-motion', value: 'reduce' }] })
      await theme(false); await render('home')
      await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'forced-colors layout overflows horizontally')
      await expect('getComputedStyle(document.querySelector(".eac-market__main")).animationName === "none" || getComputedStyle(document.querySelector(".eac-market__main")).animationDuration === "0s"', 'reduced-motion did not disable main transition')
      const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
      writeFileSync(join(output, 'forced-colors-reduced-motion.png'), Buffer.from(shot.data, 'base64'))
    })
    await check('兼容：120% 与 200% 页面缩放', async () => {
      await send('Emulation.setEmulatedMedia', { features: [] }); await theme(false)
      await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
      for (const scale of [1.2, 2]) {
        await send('Emulation.setPageScaleFactor', { pageScaleFactor: scale }); await render('long')
        await expect('document.documentElement.scrollWidth <= innerWidth + 1', `page scale ${scale} overflows horizontally`)
        const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
        writeFileSync(join(output, `page-scale-${String(scale).replace('.', '-')}.png`), Buffer.from(shot.data, 'base64'))
      }
      await send('Emulation.setPageScaleFactor', { pageScaleFactor: 1 })
    })
  }

  await check('行情表：全部插件目录变行列表且截图', async () => {
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
    await theme(false); await render('home'); await click('全部插件')
    await until('document.body.innerText.includes("个插件符合当前条件")')
    await expect('getComputedStyle(document.querySelector(".eac-market__directory-grid")).flexDirection === "column"', 'directory did not become ticker rows')
    await expect('getComputedStyle(document.querySelector(".eac-market__directory-grid .eac-market__plugin-card")).borderRadius === "0px"', 'ticker rows still look like cards')
    await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'directory ticker overflows horizontally')
    await pause(700)
    const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
    writeFileSync(join(output, 'directory-1280-light.png'), Buffer.from(shot.data, 'base64'))
  })
  await check('详情页大字带头色块与截图', async () => {
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
    await theme(false); await render('home')
    await click('查看详情')
    await until('!!document.querySelector(".eac-market__detail > .eac-market__plugin-head")')
    const head = await evaluate('(() => { const el = document.querySelector(".eac-market__detail > .eac-market__plugin-head"); const h1 = el.querySelector("h1"); const st = getComputedStyle(el); return JSON.stringify({ radius: st.borderRadius, size: parseFloat(getComputedStyle(h1).fontSize) }) })()')
    const parsed = JSON.parse(head)
    if (parseFloat(parsed.radius) < 12 || parsed.size < 30) throw new Error('detail band not rebuilt: ' + head)
    await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'detail overflows horizontally')
    await pause(700)
    const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
    writeFileSync(join(output, 'detail-1280-light.png'), Buffer.from(shot.data, 'base64'))
  })
  await check('章节流：虚线轨道与编号章节可见且截图', async () => {
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
    await theme(false); await render('home')
    await until('!!document.querySelector(".eac-market__stream")')
    const rail = await evaluate('getComputedStyle(document.querySelector(".eac-market__stream"), "::before").borderLeftWidth')
    if (rail !== '1px') throw new Error('stream rail missing: ' + rail)
    await expect('[...document.querySelectorAll(".eac-market__chapter-index")].length >= 3', 'chapter indexes missing')
    await evaluate('document.querySelector(".eac-market__discover-results")?.scrollIntoView({ block: "start" })')
    await pause(120)
    await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'chapter stream overflows horizontally')
    await pause(700)
    const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
    writeFileSync(join(output, 'stream-1280-light.png'), Buffer.from(shot.data, 'base64'))
  })
  await check('机架条：我的插件变整宽机架行且截图', async () => {
    await theme(false); await render('inventory-scroll'); await click('我的插件')
    await until('!!document.querySelector(".eac-market__system-group")')
    const card = await evaluate('(() => { const el = document.querySelector(".eac-market__grid > .eac-market__card"); if (!el) throw new Error("rack row missing"); const st = getComputedStyle(el); return JSON.stringify({ left: st.borderLeftWidth, radius: st.borderRadius, direction: getComputedStyle(el.parentElement).flexDirection }) })()')
    const parsed = JSON.parse(card)
    if (parsed.left !== '4px' || parsed.direction !== 'column') throw new Error('rack row structure wrong: ' + card)
    await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'rack overflows horizontally')
    await pause(700)
    const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
    writeFileSync(join(output, 'rack-1280-light.png'), Buffer.from(shot.data, 'base64'))
  })
  await check('微交互：按压台阶、成功彩纸与 reduced-motion 降级', async () => {
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
    await send('Emulation.setEmulatedMedia', { features: [] })
    await theme(false); await render('home')
    const primary = await evaluate("(() => { const b=[...document.querySelectorAll('.eac-button--primary')].find(x=>x.textContent.trim()==='搜索全部插件'); if(!b) throw new Error('primary button missing'); const r=b.getBoundingClientRect(); return JSON.stringify({x:r.left+r.width/2,y:r.top+r.height/2}) })()")
    const point = JSON.parse(primary)
    await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: point.x, y: point.y })
    await send('Input.dispatchMouseEvent', { type: 'mousePressed', x: point.x, y: point.y, button: 'left', clickCount: 1 })
    const pressed = await evaluate("(() => { const b=[...document.querySelectorAll('.eac-button--primary')].find(x=>x.textContent.trim()==='搜索全部插件'); const st=getComputedStyle(b); return JSON.stringify({t:st.transform, s:st.boxShadow}) })()")
    await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: point.x, y: point.y, button: 'left', clickCount: 1 })
    const press = JSON.parse(pressed)
    if (press.t !== 'none' && press.t !== 'matrix(1, 0, 0, 1, 0, 0)') throw new Error('active press still displaces the button: ' + pressed)
    if (!press.s.includes('0px 0px 0px 0px')) throw new Error('extrusion did not collapse on press: ' + pressed)
    await render('feedback-completed')
    await until('document.querySelectorAll(".eac-market__confetti i").length >= 10')
    await pause(1600)
    await expect('document.querySelectorAll(".eac-market__confetti").length === 0', 'confetti layer was not cleaned up')
    await render('feedback-failed')
    await pause(300)
    await expect('document.querySelectorAll(".eac-market__confetti").length === 0', 'failed action played confetti')
    await render('feedback-stamped')
    await pause(300)
    await expect('document.querySelectorAll(".eac-market__confetti").length === 0', 'non-milestone completed action played confetti')
    await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
    await render('feedback-completed')
    await pause(250)
    await expect('document.querySelectorAll(".eac-market__confetti").length === 0', 'reduced-motion still celebrated')
    await render('home')
    await until('!!document.querySelector(".eac-market__chapter-index")')
    const anim = await evaluate('getComputedStyle(document.querySelector(".eac-market__chapter-index")).animationName')
    if (anim !== 'none') throw new Error('chapter flip survives reduced-motion: ' + anim)
    await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: 640, y: 400 })
    await pause(80)
    const magnet = await evaluate("(() => { const b=[...document.querySelectorAll('.eac-button--primary')].find(x=>x.textContent.trim()==='搜索全部插件'); return b ? b.style.transform : '' })()")
    if (magnet) throw new Error('magnet engaged under reduced-motion: ' + magnet)
    await send('Emulation.setEmulatedMedia', { features: [] })
    await evaluate("window.__mmOrig = window.matchMedia; window.matchMedia = (q) => ((q.includes('pointer: fine') || q.includes('hover: hover')) ? { matches: true, media: q, addEventListener(){}, removeEventListener(){}, addListener(){}, removeListener(){} } : window.__mmOrig.call(window, q))")
    await render('home')
    await pause(400)
    const target2 = JSON.parse(await evaluate("(() => { const b=[...document.querySelectorAll('.eac-button--primary')].find(x=>x.textContent.trim()==='搜索全部插件'); const r=b.getBoundingClientRect(); return JSON.stringify({x:r.left + r.width * 0.25, y:r.top + r.height / 2}) })()"))
    await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: target2.x, y: target2.y })
    await pause(160)
    const magnetOn = await evaluate("(() => { const b=[...document.querySelectorAll('.eac-button--primary')].find(x=>x.textContent.trim()==='搜索全部插件'); return b.style.transform })()")
    if (!magnetOn) throw new Error('magnet did not engage on pointerenter')
    await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: target2.x + 400, y: Math.max(20, target2.y - 300) })
    await pause(160)
    const magnetOff = await evaluate("(() => { const b=[...document.querySelectorAll('.eac-button--primary')].find(x=>x.textContent.trim()==='搜索全部插件'); return b.style.transform })()")
    if (magnetOff) throw new Error('magnet did not clear on pointerleave: ' + magnetOff)
    await evaluate('window.matchMedia = window.__mmOrig; delete window.__mmOrig')
  })
  await check('任务面板：右侧真抽屉、焦点与背景 inert', async () => {
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
    await send('Emulation.setEmulatedMedia', { features: [] })
    await theme(false); await render('ai')
    await until('!!document.querySelector(".eac-modal-overlay--drawer")')
    const drawer = await evaluate(`(() => { const o = document.querySelector('.eac-modal-overlay--drawer'); const c = document.querySelector('.eac-modal--drawer'); const r = c.getBoundingClientRect(); return JSON.stringify({ overlay: o.className, w: Math.round(r.width), right: Math.round(r.right), iw: innerWidth, focus: c.contains(document.activeElement) }) })()`)
    const d = JSON.parse(drawer)
    if (!d.overlay.includes('eac-modal-overlay--drawer')) throw new Error('drawer overlay class missing: ' + drawer)
    if (d.w > 460 || Math.abs(d.right - d.iw) > 2) throw new Error('drawer not right-anchored: ' + drawer)
    if (!d.focus) throw new Error('focus not inside drawer: ' + drawer)
    await send('Emulation.setDeviceMetricsOverride', { width: 480, height: 900, deviceScaleFactor: 1, mobile: false })
    await pause(200)
    const drawer480 = await evaluate(`(() => { const c = document.querySelector('.eac-modal--drawer'); const r = c.getBoundingClientRect(); return JSON.stringify({ w: Math.round(r.width), right: Math.round(r.right), iw: innerWidth, overflow: document.documentElement.scrollWidth > innerWidth + 1 }) })()`)
    const d480 = JSON.parse(drawer480)
    if (d480.overflow || Math.abs(d480.right - d480.iw) > 2) throw new Error('drawer overflows at 480: ' + drawer480)
    await send('Emulation.setDeviceMetricsOverride', { width: 480, height: 900, deviceScaleFactor: 1, mobile: false })
    await theme(false); await render('tasks-empty')
    await until('!!document.querySelector(".eac-modal--drawer")')
    await expect('document.body.innerText.includes("暂无安装任务")', 'drawer empty state missing')
    await expect('!!document.querySelector(".eac-market__empty-mark")', 'EMPTY mark missing in drawer')
    const emptyGeo = await evaluate(`(() => { const o = document.querySelector('.eac-modal-overlay'); const c = document.querySelector('.eac-modal--drawer'); const r = c.getBoundingClientRect(); const m = document.querySelector('.eac-market').getBoundingClientRect(); return JSON.stringify({ right: Math.round(r.right), marketRight: Math.round(m.right), top: Math.round(o.getBoundingClientRect().top), marketTop: Math.round(m.top), w: Math.round(r.width) }) })()`)
    const eg = JSON.parse(emptyGeo)
    if (Math.abs(eg.right - eg.marketRight) > 2 || Math.abs(eg.top - eg.marketTop) > 2) throw new Error('drawer not aligned to market panel: ' + emptyGeo)
    await pause(350)
    const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
    writeFileSync(join(output, 'drawer-empty-480.png'), Buffer.from(shot.data, 'base64'))
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
    await theme(false); await render('remove'); await click('我的插件'); await click('卸载')
    await until('!!document.querySelector("[role=dialog]")')
    await expect('document.querySelector(".eac-market__topbar").hasAttribute("inert")', 'topbar not inert while centered dialog open')
    await evaluate(`(() => { document.getElementById('root').classList.add('official-panel-fixture'); const main = document.querySelector('.eac-market__main'); main.insertAdjacentHTML('beforeend', '<div style="height:2400px" data-pin-filler></div>') })()`)
    await pause(120)
    const pinBefore = await evaluate(`Math.round(document.querySelector('.eac-modal-overlay').getBoundingClientRect().top)`)
    await evaluate(`document.querySelector('.eac-market__scroll').scrollTo({ top: 240, behavior: 'instant' })`)
    await pause(150)
    const pinAfter = await evaluate(`Math.round(document.querySelector('.eac-modal-overlay').getBoundingClientRect().top)`)
    const scrolled = await evaluate(`document.querySelector('.eac-market__scroll').scrollTop`)
    if (scrolled < 100) throw new Error('scroller did not scroll behind dialog: scrollTop=' + scrolled)
    if (Math.abs(pinAfter - pinBefore) > 1) throw new Error(`overlay moved with content: ${pinBefore} -> ${pinAfter}`)
    await click('取消')
    await pause(200)
    await expect('!document.querySelector("[role=dialog]")', 'cancel did not close dialog')
    await expect('!document.querySelector(".eac-market__topbar").hasAttribute("inert")', 'topbar stayed inert after dialog closed')
  })
  await check('安装确认：遮罩点击不关闭高风险弹窗', async () => {
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
    await theme(false); await render('install'); await click('打开安装窗口')
    await until('!!document.querySelector("[role=dialog]")')
    await send('Input.dispatchMouseEvent', { type: 'mousePressed', x: 4, y: 4, button: 'left', clickCount: 1 })
    await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: 4, y: 4, button: 'left', clickCount: 1 })
    await pause(200)
    await expect('!!document.querySelector("[role=dialog]")', 'overlay click dismissed the install confirmation')
  })
  await check('目录分页：翻页回到结果头部', async () => {
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
    await theme(false); await render('long')
    await evaluate("document.getElementById('root').classList.add('official-panel-fixture')")
    await pause(150); await click('全部插件')
    await until('!!document.querySelector(".eac-market__pagination")')
    await evaluate('document.querySelector(".eac-market__scroll").scrollTo({ top: 99999, behavior: "instant" })')
    await pause(120)
    await click('下一页')
    await pause(350)
    const offset = await evaluate(`(() => { const meta = document.querySelector('.eac-market__directory-meta'); const sc = document.querySelector('.eac-market__scroll'); return Math.round(meta.getBoundingClientRect().top - sc.getBoundingClientRect().top) })()`)
    if (offset > 220) throw new Error('pagination did not scroll back to results head: offset=' + offset)
    await expect('document.body.innerText.includes("第 2 / ")', 'page did not advance')
  })
  await check('首推 fallback：海报与信息栏不再重复', async () => {
    await theme(false); await render('trial-broken-poster')
    await until('!!document.querySelector(".eac-market__poster--fallback")')
    await pause(300)
    const info = await evaluate(`(() => ({ copyH3: !!document.querySelector('.eac-market__poster-copy h3'), artStrong: !!document.querySelector('.eac-market__poster-art strong'), meta: !!document.querySelector('.eac-market__poster-fallback-meta') }))()`)
    if (info.copyH3) throw new Error('fallback copy still repeats the title in an h3')
    if (!info.artStrong || !info.meta) throw new Error('fallback art lost name/meta: ' + dup)
  })
  await check('轮播：自动换页更新 live 播报', async () => {
    await theme(false); await render('trial-broken-poster')
    await until('!!document.querySelector(".eac-market__poster-controls")')
    let announced = ''
    for (let i = 0; i < 30; i++) {
      announced = await evaluate(`(document.querySelector('.eac-market__poster-controls .eac-market__sr-only') || {textContent:''}).textContent`)
      if (announced && announced.includes('项，共')) break
      await pause(300)
    }
    if (!announced.includes('项，共')) throw new Error('auto rotation did not announce via live region after 9s: ' + announced)
  })
  await check('排版节奏：机架行尾、顶栏同排、频道标签贴合', async () => {
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
    await send('Emulation.setEmulatedMedia', { features: [] })
    await theme(false); await render('inventory-scroll'); await click('我的插件')
    await until('!!document.querySelector(".eac-market__system-group")')
    const rhythm = await evaluate(`(() => {
      const tails = [...document.querySelectorAll('.eac-market__grid > .eac-market__card')].map((card) => {
        const kids = [...card.children].filter((k) => getComputedStyle(k).display !== 'none' && k.getBoundingClientRect().height > 0)
        if (!kids.length) return 0
        const contentBottom = Math.max(...kids.map((k) => k.getBoundingClientRect().bottom))
        return Math.round(card.getBoundingClientRect().bottom - contentBottom)
      })
      const centers = ['.eac-market__brand', '.eac-market__nav', '.eac-market__top-actions'].map((sel) => { const r = document.querySelector(sel).getBoundingClientRect(); return r.top + r.height / 2 })
      const header = document.querySelector('.eac-market__topbar').getBoundingClientRect()
      const tabBottoms = [...document.querySelectorAll('.eac-market__nav button')].map((b) => Math.round(b.getBoundingClientRect().bottom))
      return JSON.stringify({ tails, centerSpread: Math.round((Math.max(...centers) - Math.min(...centers)) * 10) / 10, tabGap: tabBottoms.map((b) => Math.round((header.bottom - 2) - b)) })
    })()`)
    const parsed = JSON.parse(rhythm)
    const badTail = parsed.tails.find((tail) => tail > 24)
    if (badTail !== undefined) throw new Error('rack row tail too large: ' + rhythm)
    if (parsed.centerSpread > 4) throw new Error('topbar same-row center spread > 4px: ' + rhythm)
    const badGap = parsed.tabGap.find((gap) => Math.abs(gap) > 1)
    if (badGap !== undefined) throw new Error('channel tab not flush with masthead rule: ' + rhythm)
  })
  for (const [name, width, dark] of [['home', 1280, false], ['home', 480, true], ['long', 480, false], ['empty', 480, false], ['author', 480, true], ['ai', 480, true]]) {
    await check(`布局与截图 ${name}-${width}-${dark ? 'dark' : 'light'}`, async () => {
      await send('Emulation.setDeviceMetricsOverride', { width, height: 900, deviceScaleFactor: 1, mobile: false }); await theme(dark); await render(name)
      await expect('document.documentElement.scrollWidth <= innerWidth + 1', 'viewport has horizontal overflow')
      await pause(700)
      const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
      writeFileSync(join(output, `${name}-${width}-${dark ? 'dark' : 'light'}.png`), Buffer.from(shot.data, 'base64'))
    })
  }
} catch (error) { results.push({ name: 'browser harness', status: 'failed', error: error.stack }) }
finally {
  if (send) await send('Browser.close').catch(() => {})
  ws?.close(); server.close(); browser.kill()
  writeFileSync(join(output, 'browser-results.json'), JSON.stringify({ evidence: 'synthetic React components in isolated headless Edge; not official Desktop', results }, null, 2))
  console.log(JSON.stringify(results, null, 2))
  process.exitCode = results.some((result) => result.status === 'failed') ? 1 : 0
}
