import { describe, expect, it } from 'vitest'
import { createManagementBrowserHarness } from './management-browser-harness.ts'

const { evaluate, state, until, settle, click, disabled, reload } = createManagementBrowserHarness()
const ready = () => until('!!document.querySelector(".eac-market-host")')
async function start() {
  await ready()
  await click('我的插件')
  await click('停用')
  await until('fixture.calls.writes.length === 1')
}
async function failTransport() {
  await start()
  await settle('fixture.reject("writes", 0)')
  await until('document.body.textContent.includes("传输异常")')
}

describe('RW-13B 管理原意图（真实 React / 隔离 Edge）', () => {
  it.each(['applied', 'failed'])('20秒展示超时、双击、迟到 %s 不解锁或重写', async status => {
    await ready()
    await click('我的插件')
    await settle('fixture.click("停用"); fixture.click("停用")')
    await until('fixture.calls.writes.length === 1')
    const original = (await state()).calls.writes[0]!
    await settle('fixture.expire(20000)')
    expect((await state()).text).toContain('原 Promise 未结束')
    expect(await disabled('停用')).toBe(true)
    await click('停用')
    await settle('fixture.complete("writes", 0, fixture.result(' + JSON.stringify(status) + '))')
    expect((await state()).text).toContain('结果未知')
    expect(await disabled('停用')).toBe(true)
    expect((await state()).calls.writes).toEqual([original])
    expect(Object.values((await state()).pointers)[0]).toMatchObject({ environmentId: 'test-environment', packageName: original.packageName, expectedVersion: original.expectedVersion, action: 'disable', idempotencyKey: original.idempotencyKey })
    expect((await state()).errors).toEqual([])
  })
  it('not-found 不证明未写入；核对只带原身份且不刷新库存冒充完成', async () => {
    await failTransport()
    const before = await state()
    await settle('fixture.click("核对原操作"); fixture.click("核对原操作")')
    await until('fixture.calls.recover.length === 1')
    expect(await disabled('正在核对原操作…')).toBe(true)
    await settle('fixture.complete("recover", 0, { status: "not-found" })')
    const after = await state()
    const original = before.calls.writes[0]!
    expect(after.calls.recover[0]).toEqual({ packageName: original.packageName, expectedVersion: original.expectedVersion, action: 'disable', idempotencyKey: original.idempotencyKey })
    expect(after.text).toContain('不证明未写入')
    expect(after.calls.writes).toHaveLength(1)
    expect(after.calls.removes).toHaveLength(0)
    expect(after.inventoryReads).toBe(before.inventoryReads)
    expect(after.pointers).toEqual(before.pointers)
    expect(await disabled('停用')).toBe(true)
  })
  it.each(['missing', 'unknown'])('旧记录 %s 仅 receipt 不能解除保护', async kind => {
    await failTransport()
    await click('核对原操作')
    await until('fixture.calls.recover.length === 1')
    await settle('fixture.complete("recover", 0, { status: "found", stage: "settled", receipt: fixture.result("applied"), ' + (kind === 'unknown' ? 'result: fixture.result("unknown")' : '') + ' })')
    expect((await state()).text).toContain('官方回执：applied')
    expect((await state()).text).toContain('结果未知')
    expect(await disabled('停用')).toBe(true)
    expect(Object.keys((await state()).pointers)).toHaveLength(1)
    expect((await state()).calls.writes).toHaveLength(1)
  })
  it.each(['applied', 'restart-required', 'failed'])('完整 %s 解除未知保护并保留真实语义', async status => {
    await failTransport()
    await click('核对原操作')
    await until('fixture.calls.recover.length === 1')
    await settle('fixture.complete("recover", 0, fixture.recovery(' + JSON.stringify(status) + ', ' + (status === 'failed' ? 'false' : 'true') + '))')
    expect((await state()).text).toContain('原业务结果：' + status)
    expect((await state()).text).toContain(status === 'applied' ? '已完成' : status === 'restart-required' ? '需要重新核对' : '失败')
    expect(Object.keys((await state()).pointers)).toHaveLength(0)
    expect(await disabled('停用')).toBe(false)
    expect((await state()).calls.writes).toHaveLength(1)
  })
  it('失败但 changed/权限变化保留部分完成；库存刷新失败不篡改原回执', async () => {
    await failTransport()
    await click('核对原操作')
    await until('fixture.calls.recover.length === 1')
    await settle('fixture.inventoryFailure = true; fixture.complete("recover", 0, { ...fixture.recovery("failed"), result: { ...fixture.result("failed"), error: "maintenance failed", permissionChanges: [{ packageName: "alpha", decision: "revoked" }] } })')
    expect((await state()).text).toContain('部分完成')
    expect((await state()).text).toContain('alpha：revoked')
    expect((await state()).text).toContain('不改变原业务回执')
    expect(await disabled('停用')).toBe(false)
  })
  it('可信只读终态到达时原写 Promise 未结束仍保持在途锁', async () => {
    await start()
    await settle('fixture.expire(20000)')
    await click('核对原操作')
    await until('fixture.calls.recover.length === 1')
    await settle('fixture.complete("recover", 0, fixture.recovery())')
    expect((await state()).text).toContain('原业务结果：applied')
    expect(Object.keys((await state()).pointers)).toHaveLength(0)
    expect(await disabled('停用')).toBe(true)
    await click('停用')
    expect((await state()).calls.writes).toHaveLength(1)
    expect((await state()).calls.removes).toHaveLength(0)
    await settle('fixture.reject("writes", 0)')
    expect(await disabled('停用')).toBe(false)
    expect((await state()).text).toContain('原业务结果：applied')
    expect((await state()).calls.writes).toHaveLength(1)
  })

  it.each(['write', 'recover'])('%s applied 后 removeItem 抛错仍展示原结果，保留指针并阻止新写', async source => {
    await start()
    const before = await state()
    if (source === 'recover') {
      await settle('fixture.reject("writes", 0)')
      await click('核对原操作')
      await until('fixture.calls.recover.length === 1')
    }
    await settle('fixture.savedRemoveItem = Storage.prototype.removeItem; Storage.prototype.removeItem = function(key) { if (key.startsWith("eac-market:management:")) throw new Error("storage clear denied"); return fixture.savedRemoveItem.call(this, key) }')
    try {
      await settle(source === 'recover' ? 'fixture.complete("recover", 0, fixture.recovery())' : 'fixture.complete("writes", 0, fixture.result())')
      await until('document.body.textContent.includes("本地指针未能安全清除")')
      const after = await state()
      expect(after.text).toContain('原业务结果：applied')
      expect(after.text).toContain('结果未知')
      expect(after.pointers).toEqual(before.pointers)
      expect(await disabled('停用')).toBe(true)
      expect(await disabled('卸载')).toBe(true)
      await settle('fixture.click("停用"); fixture.click("卸载")')
      const blocked = await state()
      expect(blocked.calls.writes).toEqual(before.calls.writes)
      expect(blocked.calls.removes).toHaveLength(0)
      expect(blocked.pointers).toEqual(before.pointers)
      expect(blocked.text).toContain('原业务结果：applied')
      expect(blocked.errors).toEqual([])
    } finally {
      await settle('Storage.prototype.removeItem = fixture.savedRemoveItem; delete fixture.savedRemoveItem')
    }
  })
  it('导航保留原指针，组件卸载重挂只读恢复，旧回包不污染', async () => {
    await start()
    const original = (await state()).calls.writes[0]!
    await click('发现')
    expect((await state()).text).toContain('原目标：' + original.packageName)
    await settle('fixture.unmount(); fixture.render()')
    await ready()
    await until('fixture.calls.recover.length === 1')
    await settle('fixture.complete("writes", 0, fixture.result("applied"))')
    expect(Object.keys((await state()).pointers)).toHaveLength(1)
    await settle('fixture.complete("recover", 0, fixture.recovery("restart-required"))')
    expect((await state()).text).toContain('原业务结果：restart-required')
    expect((await state()).calls.writes).toHaveLength(1)
    expect((await state()).errors).toEqual([])
  })
  it('重连恢复原 key，旧核对迟到结果不覆盖新连接', async () => {
    await failTransport()
    await click('核对原操作')
    await until('fixture.calls.recover.length === 1')
    await settle('fixture.reconnect()')
    await ready()
    await until('fixture.calls.recover.length === 2')
    expect((await state()).calls.recover[1]).toEqual((await state()).calls.recover[0])
    await settle('fixture.complete("recover", 1, fixture.recovery("failed", false)); fixture.complete("recover", 0, fixture.recovery("applied"))')
    expect((await state()).text).toContain('原业务结果：failed')
    expect((await state()).text).not.toContain('原业务结果：applied')
    expect((await state()).calls.writes).toHaveLength(1)
  })
  it('真实页面重开只恢复最小指针，不自动重写', async () => {
    await failTransport()
    const original = Object.values((await state()).pointers)[0]!
    await reload()
    await until('fixture.calls.recover.length === 1')
    expect((await state()).calls.writes).toHaveLength(0)
    expect((await state()).calls.removes).toHaveLength(0)
    expect((await state()).calls.recover[0]).toEqual({ packageName: original.packageName, expectedVersion: original.expectedVersion, action: original.action, idempotencyKey: original.idempotencyKey })
    await settle('fixture.complete("recover", 0, { status: "not-found" })')
    expect(Object.values((await state()).pointers)[0]).toEqual(original)
  })
  it('换环境不会向新环境查询旧指针；回到原环境继续原 key', async () => {
    await failTransport()
    const original = Object.values((await state()).pointers)[0]!
    await settle('fixture.environment = "other-environment"; fixture.reconnect()')
    await ready()
    expect((await state()).calls.recover).toHaveLength(0)
    await click('我的插件')
    expect(await disabled('停用')).toBe(false)
    await settle('fixture.environment = "test-environment"; fixture.reconnect()')
    await ready()
    await until('fixture.calls.recover.length === 1')
    expect((await state()).calls.recover[0]!.idempotencyKey).toBe(original.idempotencyKey)
    expect((await state()).calls.writes).toHaveLength(1)
  })
  it.each(['method', 'capability'])('旧 Host 缺 %s 诚实 fallback，仍不写入', async kind => {
    await failTransport()
    await settle(kind === 'method' ? 'fixture.oldHost = true; fixture.reconnect()' : 'fixture.noCapability = true; fixture.reconnect()')
    await ready()
    await until('document.body.textContent.includes("未开放原管理操作查询能力")')
    expect((await state()).calls.recover).toHaveLength(0)
    expect((await state()).calls.writes).toHaveLength(1)
    await click('到官方插件页核对')
    expect((await state()).official).toBe(1)
  })
  it('缺写方法确定未提交，不生成指针', async () => {
    await ready()
    await settle('fixture.noWrite = true; fixture.reconnect()')
    await ready()
    await click('我的插件')
    await click('停用')
    await until('document.body.textContent.includes("确定未提交")')
    expect((await state()).calls.writes).toHaveLength(0)
    expect(Object.keys((await state()).pointers)).toHaveLength(0)
    expect(await disabled('停用')).toBe(false)
  })
  it('卸载两次确认与取消不写入；确认后只提交一次原 remove', async () => {
    await ready()
    await click('我的插件')
    await click('卸载')
    expect((await state()).calls.removes).toHaveLength(0)
    await click('继续查看卸载影响')
    await click('取消')
    expect((await state()).calls.removes).toHaveLength(0)
    await click('卸载')
    await click('继续查看卸载影响')
    await settle('fixture.click("已了解影响，再次确认卸载"); fixture.click("已了解影响，再次确认卸载")')
    await until('fixture.calls.removes.length === 1')
    await click('取消')
    await settle('fixture.reject("removes", 0)')
    await click('核对原操作')
    await until('fixture.calls.recover.length === 1')
    const before = await state()
    expect(before.calls.recover[0]).toMatchObject({ action: 'remove', idempotencyKey: before.calls.removes[0]!.idempotencyKey })
    expect(before.calls.removes[0]!.confirmed).toBe(true)
    await settle('fixture.complete("recover", 0, fixture.recovery())')
    expect((await state()).calls.removes).toHaveLength(1)
    expect((await state()).calls.writes).toHaveLength(0)
  })

  it.each(['enable', 'disable'])('直接 %s 成功后只有明确新操作才生成新 key', async action => {
    await ready()
    await settle('fixture.inventoryEnabled = ' + (action === 'disable' ? 'true' : 'false') + '; fixture.reconnect()')
    await ready()
    await click('我的插件')
    const button = action === 'enable' ? '启用' : '停用'
    await click(button)
    await until('fixture.calls.writes.length === 1')
    const original = (await state()).calls.writes[0]!
    expect(original.enabled).toBe(action === 'enable')
    await settle('fixture.complete("writes", 0, fixture.result())')
    expect((await state()).text).toContain('原业务结果：applied')
    expect((await state()).calls.recover).toHaveLength(0)
    expect(Object.keys((await state()).pointers)).toHaveLength(0)
    await click(button)
    await until('fixture.calls.writes.length === 2')
    expect((await state()).calls.writes[1]!.idempotencyKey).not.toBe(original.idempotencyKey)
    await settle('fixture.complete("writes", 1, fixture.result())')
  })
  it.each(['write', 'recover'])('%s 回包期间真实环境变化不解除原环境保护', async kind => {
    await start()
    const original = Object.values((await state()).pointers)[0]!
    if (kind === 'recover') {
      await settle('fixture.reject("writes", 0)')
      await click('核对原操作')
      await until('fixture.calls.recover.length === 1')
    }
    await settle('fixture.environment = "foreign-environment"; fixture.complete(' + JSON.stringify(kind === 'write' ? 'writes' : 'recover') + ', 0, ' + (kind === 'write' ? 'fixture.result()' : 'fixture.recovery()') + ')')
    expect((await state()).text).toContain('连接环境已变化')
    expect((await state()).text).not.toContain('原业务结果：applied')
    expect(Object.values((await state()).pointers)[0]).toEqual(original)
    expect((await state()).calls.writes).toHaveLength(1)
  })
  it('不完整 result 不能冒充可信终态', async () => {
    await failTransport()
    await click('核对原操作')
    await until('fixture.calls.recover.length === 1')
    await settle('fixture.complete("recover", 0, { status: "found", stage: "settled", receipt: fixture.result(), result: { status: "applied" } })')
    expect((await state()).text).toContain('没有返回有效的完整业务结果')
    expect(Object.keys((await state()).pointers)).toHaveLength(1)
    expect(await disabled('停用')).toBe(true)
    expect((await state()).errors).toEqual([])
  })
  it('市场自身与系统组件仍只允许官方入口，不产生管理写入', async () => {
    await ready()
    await settle('fixture.extraItems = [{ packageName: "@dsh-eac/market", version: "0.1.0", installed: true, bundleEnabled: true, source: "profile", removable: true, rows: [], restartRequired: false }, { packageName: "@deepseek-ai/system-fixture", installed: true, bundleEnabled: true, source: "installation", removable: false, readOnlyReason: "management-required", rows: [], restartRequired: false }]; fixture.reconnect()')
    await ready()
    await click('我的插件')
    await settle('const summary = [...document.querySelectorAll("summary")].find(element => element.textContent.includes("官方与系统组件")); if (summary) summary.click()')
    const protectedCards = await evaluate<number>('(() => { const cards = [...document.querySelectorAll("article")].filter(card => card.textContent.includes("@dsh-eac/market") || card.textContent.includes("@deepseek-ai/system-fixture")); for (const card of cards) for (const button of card.querySelectorAll("button")) if (["停用", "卸载"].includes(button.textContent)) { if (!button.disabled) throw new Error("保护按钮被启用"); button.click() } return cards.length })()')
    expect(protectedCards).toBe(2)
    expect((await state()).calls.writes).toHaveLength(0)
    expect((await state()).calls.removes).toHaveLength(0)
    expect((await state()).errors).toEqual([])
  })
  it('React StrictMode 重挂不自动重复提交', async () => {
    await failTransport()
    await settle('fixture.strict = true; fixture.render()')
    await ready()
    await until('fixture.calls.recover.length >= 1')
    expect((await state()).calls.writes).toHaveLength(1)
    const count = (await state()).calls.recover.length
    await settle('fixture.complete("recover", ' + (count - 1) + ', { status: "not-found" })')
    expect(Object.keys((await state()).pointers)).toHaveLength(1)
  })
})
