import { describe, expect, it } from 'vitest'
import { createTaskBrowserHarness } from './task-browser-harness.ts'

const { evaluate, state, until, settle, click, disabled, readyProposal } = createTaskBrowserHarness()


describe('TaskCard 迟回包与只读核对（真实 React / 隔离 Edge）', () => {
  it.each(['task', 'environment', 'remote'])('更换 %s 后旧分析不能显示，不能解锁新分析', async identity => {
    await click('AI 分析本任务')
    await settle('fixture.oldProposal = fixture.proposal()')
    if (identity === 'task') await settle('fixture.render({ taskId: "task-2" })')
    else if (identity === 'environment') await settle('fixture.render({ environmentId: "environment-2" })')
    else await settle('fixture.remote = fixture.makeRemote(); fixture.render()')
    await click('AI 分析本任务')
    await settle('fixture.complete("analyze", 0, fixture.oldProposal)')
    expect((await state()).text).not.toContain('仅属于 task-1 的方案')
    expect(await disabled('AI 分析本任务')).toBe(true)
    await settle('fixture.complete("analyze", 1, fixture.proposal())')
    expect((await state()).text).toContain('的方案')
    expect(await disabled('AI 分析本任务')).toBe(false)
  })
  it.each(['resolve', 'reject'])('换 task 旧取消 %s 不调用 onChanged/不污染新卡', async result => {
    await settle('fixture.render({ status: "installing" }); fixture.oldTask = fixture.task')
    await click('取消任务')
    await settle('fixture.render({ taskId: "task-2" })')
    await click('取消任务')
    if (result === 'resolve') await settle('fixture.complete("cancel", 0, { ...fixture.oldTask, status: "cancelled" })')
    else await settle('fixture.reject("cancel", 0, "旧任务错误不该显示")')
    expect((await state()).changed).toEqual([])
    expect((await state()).text).not.toContain('旧任务错误不该显示')
    expect(await disabled('取消任务')).toBe(true)
    await settle('fixture.complete("cancel", 1, fixture.task)')
    expect((await state()).changed[0]!.taskId).toBe('task-2')
  })
  it('换 remote 后旧 AI 确认不能触发读取/refresh或解除新卡写锁', async () => {
    await readyProposal()
    await click('确认执行 AI 方案')
    await settle('fixture.remote = fixture.makeRemote(); fixture.render()')
    await readyProposal()
    await click('确认执行 AI 方案')
    await settle('fixture.complete("confirm", 0, { status: "queued", changed: false, taskId: "late-execution" })')
    expect((await state()).calls.read).toEqual([])
    expect((await state()).refreshes).toBe(0)
    expect(await disabled('确认执行 AI 方案')).toBe(true)
    await settle('fixture.complete("confirm", 1, { status: "unknown", changed: false })')
    expect((await state()).text).toContain('后台没有返回可确认的最终结果')
  })
  it('AI 确认后的执行任务读取仍受同一 scope 约束', async () => {
    await readyProposal()
    await click('确认执行 AI 方案')
    await settle('fixture.complete("confirm", 0, { status: "queued", changed: false, taskId: "execution-task" })')
    await until('fixture.calls.read.length === 1')
    await settle('fixture.render({ taskId: "task-2" })')
    await settle('fixture.complete("read", 0, { ...fixture.task, taskId: "execution-task" })')
    expect((await state()).changed).toEqual([])
    expect((await state()).refreshes).toBe(0)
    expect((await state()).text).not.toContain('方案已排队')
  })
  it('历史在途 updatedAt 不丢页/不叠加请求且显示最新摘要事件', async () => {
    await settle('fixture.openHistory()')
    await until('fixture.calls.events.length === 1')
    await settle('fixture.render({ updatedAt: "2026-10-04T08:00:00Z", events: [...fixture.task.events, { sequence: 9, at: "2026-10-04T08:00:00Z", phase: "partial", level: "warning", message: "最新摘要事件" }] })')
    await settle('fixture.complete("events", 0, fixture.history())')
    expect((await state()).text).toContain('完整历史')
    expect((await state()).text).toContain('最新摘要事件')
    expect((await state()).calls.events).toHaveLength(1)
  })
  it.each(['task', 'remote'])('更换 %s 使旧历史回包失效', async identity => {
    await settle('fixture.openHistory()')
    await until('fixture.calls.events.length === 1')
    if (identity === 'task') await settle('fixture.render({ taskId: "task-2" })')
    else await settle('fixture.remote = fixture.makeRemote(); fixture.render()')
    await settle('fixture.openHistory()')
    await until('fixture.calls.events.length === 2')
    await settle('fixture.complete("events", 0, fixture.history("旧历史不能显示"))')
    expect((await state()).text).not.toContain('旧历史不能显示')
    expect((await state()).text).toContain('正在读取任务记录')
    await settle('fixture.complete("events", 1, fixture.history("新任务完整历史"))')
    expect((await state()).text).toContain('新任务完整历史')
  })
  it('只读核对与超时写锁并行，但不解锁/刷新目录/重分析/猜恢复key', async () => {
    await settle('fixture.render({ status: "installing" })')
    await click('取消任务')
    await settle('fixture.expire(12000)')
    await click('重新核对')
    expect((await state()).calls.read).toEqual([{ taskId: 'task-1' }])
    await settle('fixture.render({ updatedAt: "2026-10-04T09:00:00Z" })')
    await click('重新核对本任务')
    expect((await state()).calls.read).toHaveLength(1)
    await settle('fixture.complete("read", 0, { ...fixture.task, nextAction: "只读事实：原请求仍在执行" })')
    expect((await state()).changed[0]!.nextAction).toBe('只读事实：原请求仍在执行')
    expect(await disabled('取消任务')).toBe(true)
    expect((await state()).calls.analyze).toEqual([])
    expect((await state()).calls.confirm).toEqual([])
    expect((await state()).refreshes).toBe(0)
    expect((await state()).catalogRefreshes).toBe(0)
    expect((await state()).recoveries).toBe(0)
  })
  it('只读核对保留原方案与 sourceId，不用重新分析替代核对', async () => {
    await readyProposal()
    await click('重新核对本任务')
    await settle('fixture.complete("read", 0, { ...fixture.task, updatedAt: "2026-10-04T10:00:00Z" }); fixture.render({ updatedAt: "2026-10-04T10:00:00Z" })')
    expect((await state()).calls.analyze).toHaveLength(1)
    expect((await state()).catalogRefreshes).toBe(0)
    expect((await state()).text).toContain('使用已登记来源重试')
    expect((await state()).text).toContain('仅属于 task-1 的方案')
    await click('确认执行 AI 方案')
    expect((await state()).calls.confirm[0]).toMatchObject({ proposalId: 'proposal-task-1', impactDigest: 'impact-task-1', confirmed: true })
    expect(await evaluate('fixture.lastProposal.proposal.actions[0].sourceId')).toBe('source-original')
  })
  it.each(['task', 'environment'])('核对返回错误 %s 不调用 onChanged', async identity => {
    await click('重新核对本任务')
    await settle('fixture.complete("read", 0, { ...fixture.task, ' + (identity === 'task' ? 'taskId' : 'environmentId') + ': "wrong" })')
    expect((await state()).changed).toEqual([])
    expect((await state()).text).toContain('核对结果不属于本任务或当前环境')
  })
  it('核对超时不叠加请求，原 promise 结束才允许再次核对', async () => {
    await click('重新核对本任务')
    await settle('fixture.expire(12000)')
    expect(await disabled('重新核对本任务')).toBe(true)
    await click('重新核对本任务')
    expect((await state()).calls.read).toHaveLength(1)
    await settle('fixture.complete("read", 0, fixture.task)')
    expect((await state()).changed).toEqual([])
    expect(await disabled('重新核对本任务')).toBe(false)
  })
  it('换 remote 旧核对不能更新事实或解锁新核对', async () => {
    await click('重新核对本任务')
    await settle('fixture.remote = fixture.makeRemote(); fixture.render()')
    await click('重新核对本任务')
    await settle('fixture.complete("read", 0, fixture.task)')
    expect((await state()).changed).toEqual([])
    expect(await disabled('重新核对本任务')).toBe(true)
    await settle('fixture.complete("read", 1, fixture.task)')
    expect((await state()).changed).toHaveLength(1)
  })
  it('旧 Host 无 getTask 只调用既有 onRefresh，不臆造恢复能力', async () => {
    await settle('fixture.remote = { ...fixture.makeRemote(), getTask: undefined, taskStartRecover: undefined, pluginActionRecover: undefined }; fixture.render()')
    await click('重新核对本任务')
    expect((await state()).refreshes).toBe(1)
    expect((await state()).catalogRefreshes).toBe(0)
    expect((await state()).calls.analyze).toEqual([])
    expect((await state()).calls.read).toEqual([])
    expect((await state()).errors).toEqual([])
  })
  it('历史超时不能叠加读请求；迟到历史丢弃，原请求结束后才能重读', async () => {
    await settle('fixture.openHistory()')
    await until('fixture.calls.events.length === 1')
    await settle('fixture.expire(12000)')
    expect(await disabled('重新读取任务记录')).toBe(true)
    await click('重新读取任务记录')
    expect((await state()).calls.events).toHaveLength(1)
    await settle('fixture.complete("events", 0, fixture.history("超时旧历史不能显示"))')
    expect((await state()).text).not.toContain('超时旧历史不能显示')
    expect(await disabled('重新读取任务记录')).toBe(false)
    await click('重新读取任务记录')
    expect((await state()).calls.events).toHaveLength(2)
    await settle('fixture.complete("events", 1, fixture.history("重新读取的真实历史"))')
    expect((await state()).text).toContain('重新读取的真实历史')
  })
  it('关闭抽屉使旧分析/历史回包失效，重开不显示旧方案', async () => {
    await click('AI 分析本任务')
    await settle('fixture.oldProposal = fixture.proposal(); fixture.openHistory()')
    await until('fixture.calls.events.length === 1')
    await settle('fixture.open = false; fixture.render()')
    await settle('fixture.complete("analyze", 0, fixture.oldProposal); fixture.complete("events", 0, fixture.history("关闭前的迟到历史"))')
    expect((await state()).changed).toEqual([])
    expect((await state()).refreshes).toBe(0)
    await settle('fixture.open = true; fixture.render(); fixture.openHistory()')
    expect((await state()).text).not.toContain('仅属于 task-1 的方案')
    expect((await state()).text).not.toContain('关闭前的迟到历史')
    expect((await state()).errors).toEqual([])
  })
  it.each(['cancel', 'approve', 'resume'])('%s 回执属于另一任务时不传播', async kind => {
    const button = kind === 'cancel' ? '取消任务' : kind === 'approve' ? '同意运行清单内脚本并继续' : '已重启，重新核对'
    await settle('fixture.render(' + JSON.stringify({ status: kind === 'cancel' ? 'installing' : kind === 'approve' ? 'awaiting-approval' : 'awaiting-resume', approval: { id: 'approval', attemptId: 'attempt', digest: 'digest', packages: ['@example/alpha'] }, resume: { id: 'resume', digest: 'digest', remainingPluginIds: ['plugin-alpha'] } }) + ')')
    await click(button)
    await settle('fixture.complete(' + JSON.stringify(kind) + ', 0, { ...fixture.task, taskId: "wrong-task" })')
    expect((await state()).changed).toEqual([])
    expect((await state()).text).toContain('不属于本任务或当前环境')
    expect((await state()).errors).toEqual([])
  })
})
